### ISSUE TITLE
Running Local Ursula Fleet Python Script doesn't work.

### ISSUE THREAD

**Issue by afrancht** [nucypher/nucypher#1307]
I cannot run a local fleet of Ursulas with a teacher node already running on localhost.

More detailed information can be found here including a video showing how the error occurs:

https://github.com/afrancht/NCErrors/blob/master/ErrorReport3-CannotRunUrsulaFleet.md

**Comment by michwill** [comment]
Do you take the code from master?

I don't see the typo `strtoobool` in the code which you see in the traceback (and cannot reproduce): https://github.com/nucypher/nucypher/blob/master/nucypher/cli/config.py#L38

So I am wondering, how did you obtain the nucypher code you're having

**Comment by derekpierre** [comment]
`strtoobool` was previously fixed via #1295

**Comment by afrancht** [comment]
I just pulled from your master branch into my fork and it still doesn't work for me.

**Comment by michwill** [comment]
In case you made a "non-editable installation", do from the root of the code (in the virtual environment):
```
pip3 uninstall nucypher
pip3 install -e .
```

**Comment by afrancht** [comment]
Uh now it works. What happened there eaxctly?

**Comment by michwill** [comment]
You did `pipenv install` without `--dev`. It _copied_ nucypher repository to virtual environment's site-packages and started using from there. So it disregarded the local copy you had.
I suggested to install in a different way, when you can make local edits, and they're immediately reflected (e.g. not copying the code somewhere to site-packages)

**Comment by afrancht** [comment]
That's strange, I just double-checked my command history in the terminal and I seemed to have ran `pipenv install --dev --three --skip-lock --pre` but I ran `pip3 install -U nucypher` after that to make sure I could use the cli, do you think that may have overwritten the previous?

**Comment by michwill** [comment]
Ah yes, indeed. It was `pip install -U` which screwed it up

**Comment by afrancht** [comment]
So if I use the codebase I have to use the `$ python ...` commands instead of the `nucypher alice run...`?

**Comment by michwill** [comment]
No, it will still create entrypoints in your virtualenv's `bin`

**Comment by afrancht** [comment]
I'm not sure what that means, does it mean it will still install the nucypher cli or that it will not?

**Comment by michwill** [comment]
It will

**Comment by afrancht** [comment]
Got it! Thanks!

**Comment by KPrasch** [comment]
:+1: Yup! There is not a separate installation step - installing nucypher with `pip` in enough to install both the CLI and the rest of the deps. since it is one python package.

**Comment by michwill** [comment]
That said, does it mean we have a faulty package in pypi?
